spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp.use_jdbc_metadata_defaults: false
        order_inserts: true
        order_updates: true
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
  h2:
    console:
      enabled: true

logging:
  level:
    jdbc:
      sqlonly: info
      resultsettable: info
      sqltiming: fatal
      audit: fatal
      resultset: fatal
      connection: info

    org:
      springframework.orm.jpa: debug
      hibernate.jdbc: debug
    com.nullspace.multitenant.demo: debug

app:
  name: api-user-management

jwt:
  header: Authorization
  expires_in: 900 # 5 minutes
  secret: queenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoriaqueenvictoria

tenantRuntimePath: tenants/atRuntime/
tenantStartupPath: tenants/onStartUp/
databaseBaseUrl: jdbc:postgresql://localhost:5432/